name: New Prod Build Movie Guessing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     with:
      ref: ${{ github.head_ref }}
    - name: Build Docker Image
      run: |
        echo "production build started... "
        COMMIT_ID=`echo $(git rev-parse HEAD)`
        COMMIT_ID_SHORT=`echo $(git rev-parse HEAD) | cut -c1-7`
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        IMAGE_TAG=alexjohnwilkinson/movie-guessing:$COMMIT_ID_SHORT
        IMAGE_TAG_LATEST=alexjohnwilkinson/movie-guessing:latest
        echo "new image tag created $IMAGE_TAG"
        echo "building docker image"
        docker build --file Dockerfile --build-arg ACCESS_TOKEN=${{secrets.ACCESS_TOKEN }} --build-arg SHEET_BEST_URL=${{secrets.SHEET_BEST_URL }} --tag $IMAGE_TAG --tag $IMAGE_TAG_LATEST .
        echo "new docker image complete"
        echo "pushing to docker hub"
        docker push $IMAGE_TAG_LATEST
        echo "production build complete, new image $IMAGE_TAG created and avaliable on docker hub"
